// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Memory struct {
	Key        string
	TargetType string
	TargetName string
	AnalyzedAt int64
	RunID      sql.NullInt64
}

type Run struct {
	ID           int64
	Status       string
	ErrorMessage sql.NullString
	StartedAt    int64
	FinishedAt   sql.NullInt64
}
