// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Run struct {
	ID           int64
	Status       string
	ErrorMessage sql.NullString
	StartedAt    int64
	FinishedAt   sql.NullInt64
}
