// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const insertRun = `-- name: InsertRun :one
insert into runs (id, started_at, status) values (?, ?, 'running') returning id
`

type InsertRunParams struct {
	ID        int64
	StartedAt int64
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRun, arg.ID, arg.StartedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRuns = `-- name: ListRuns :many
select id, status, error_message, started_at, finished_at from runs order by started_at desc
`

func (q *Queries) ListRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRun = `-- name: UpdateRun :exec
update runs set status = ?, finished_at = ?, error_message = ? where id = ?
`

type UpdateRunParams struct {
	Status       string
	FinishedAt   sql.NullInt64
	ErrorMessage sql.NullString
	ID           int64
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
