// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const hasMemoryKey = `-- name: HasMemoryKey :one
select exists(select 1 from memories where key = ?) as has_key
`

func (q *Queries) HasMemoryKey(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasMemoryKey, key)
	var has_key int64
	err := row.Scan(&has_key)
	return has_key, err
}

const insertFinding = `-- name: InsertFinding :exec
insert or ignore into findings (run_id, target_type, target_name, rule_name, rule_description, content_key, location, match)
values (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFindingParams struct {
	RunID           int64
	TargetType      string
	TargetName      string
	RuleName        string
	RuleDescription string
	ContentKey      string
	Location        string
	Match           string
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertFinding,
		arg.RunID,
		arg.TargetType,
		arg.TargetName,
		arg.RuleName,
		arg.RuleDescription,
		arg.ContentKey,
		arg.Location,
		arg.Match,
	)
	return err
}

const insertRun = `-- name: InsertRun :one
insert into runs (started_at, status) values (?, 'running') returning id
`

func (q *Queries) InsertRun(ctx context.Context, startedAt int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRun, startedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listFindings = `-- name: ListFindings :many
select id, run_id, target_type, target_name, rule_name, rule_description, content_key, location, "match", detected_at from findings order by detected_at desc
`

func (q *Queries) ListFindings(ctx context.Context) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TargetType,
			&i.TargetName,
			&i.RuleName,
			&i.RuleDescription,
			&i.ContentKey,
			&i.Location,
			&i.Match,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
select id, status, error_message, started_at, finished_at from runs order by started_at desc
`

func (q *Queries) ListRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemoryKey = `-- name: SetMemoryKey :exec
insert or ignore into memories (key, target_type, target_name, run_id) values (?, ?, ?, ?)
`

type SetMemoryKeyParams struct {
	Key        string
	TargetType string
	TargetName string
	RunID      sql.NullInt64
}

func (q *Queries) SetMemoryKey(ctx context.Context, arg SetMemoryKeyParams) error {
	_, err := q.db.ExecContext(ctx, setMemoryKey,
		arg.Key,
		arg.TargetType,
		arg.TargetName,
		arg.RunID,
	)
	return err
}

const updateRun = `-- name: UpdateRun :exec
update runs set status = ?, finished_at = ?, error_message = ? where id = ?
`

type UpdateRunParams struct {
	Status       string
	FinishedAt   sql.NullInt64
	ErrorMessage sql.NullString
	ID           int64
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
