// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"
)

const getActiveRun = `-- name: GetActiveRun :one
select id, started_at, finished_at from runs where finished_at is null limit 1
`

func (q *Queries) GetActiveRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getActiveRun)
	var i Run
	err := row.Scan(&i.ID, &i.StartedAt, &i.FinishedAt)
	return i, err
}
